language: java

before_install:
  - echo "MAVEN_OPTS='-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:-UseGCOverheadLimit'" > ~/.mavenrc

install: skip
script: travis_wait 60 mvn -q test jacoco:report coveralls:report -pl httpsnippet

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - .autoconf
    - $HOME/.m2
after_success:
  - mvn cobertura:cobertura -pl httpsnippet && bash <(curl -s https://codecov.io/bash)